### ISSUE TITLE
Generate the metrics from the backtest i.e total return, maxdrawdown.

### ISSUE THREAD

**Issue by hillaryke** [10ac-week9-group4/Backtesting-Infrastructure-CryptoTrading#17]
The following metrics should generated from every strategy backtest:

1. Total Return
2. Number of trades
3. Winning trades
4. Losing trades
5. Max drawdown
6. Sharpe ratio

Return the metrics in form of a dictionary with the name of the metric being the Key in the dictionary.

**Comment by mahbubah** [comment]
Metrices generated
